import { render } from "@dlightjs/dlight"
import App from "./App.view"
import For from "./forNode/For.view"
import If from "./ifNode/If.view"
import Function from "./introduction/Function.view"
import Hello from "./introduction/Hello.view"
import Reactivity from "./introduction/Reactivity.view"
import Variable from "./introduction/Variable.view"
import RootComp from "./envNode/RootComp.view"
import InlineStyle from "./style/InlineStyle.view"
import ParentComp from "./nestComp/basic/ParentNode.view"
import ParentCompF from "./forwardProps/ParentComp.view"
import ReactiveStatement from "./introduction/ReactiveStatement.view"
import IfElse from "./ifNode/ifelse.view"
import InlineHandler from "./events/InlineHandler.view"
import AddEvent from "./events/AddEvent.view"
import Element from "./element/Element.view"
import NestHtml from "./introduction/nestHtml.view"
import TextInput from "./inputs/TextInput.view"
import RadioInput from "./inputs/RadioInput.view"
import Image from "./introduction/Image.view"
import Link from "./introduction/Link.view"
import ViewWithSnippet from "./snippet/ViewWithSnippet.view"
import ContentView from "./nestComp/content/Content.view"
import ChildrenView from "./nestComp/children/Children.view"
import DidMount from "./lifeCycle/didMount.view"
import WillMount from "./lifeCycle/willMount.view"
import Expression from "./expression/Expression.view"
import PropViewClass from "./propView/PropView.view"
import CheckboxInput from "./inputs/CheckboxInput.view"
import CompElement from "./element/CompElement.view"
import Svg from "./introduction/Svg.view"

render("main", Svg)
