/**
 * @brief HTML attribute name map, from CamelCase to kebab-case
 */
export const alteredAttrMap = {
  acceptCharset: "accept-charset",
  colSpan: "colspan",
  contentEditable: "contenteditable",
  formAction: "formaction",
  formEnctype: "formenctype",
  formMethod: "formmethod",
  formNoValidate: "formnovalidate",
  formTarget: "formtarget",
  httpEquiv: "http-equiv",
  intrinsicSize: "intrinsicsize",
  inputMode: "inputmode",
  itemProp: "itemprop",
  maxLength: "maxlength",
  minLength: "minlength",
  noValidate: "novalidate",
  playsInline: "playsinline",
  referrerPolicy: "referrerpolicy",
  rowSpan: "rowspan",
  tabIndex: "tabindex",
  ariaAutocomplete: "aria-autocomplete",
  ariaChecked: "aria-checked",
  ariaDisabled: "aria-disabled",
  ariaErrormessage: "aria-errormessage",
  ariaExpanded: "aria-expanded",
  ariaHaspopup: "aria-haspopup",
  ariaHidden: "aria-hidden",
  ariaInvalid: "aria-invalid",
  ariaLabel: "aria-label",
  ariaLevel: "aria-level",
  ariaModal: "aria-modal",
  ariaMultiline: "aria-multiline",
  ariaMultiselectable: "aria-multiselectable",
  ariaOrientation: "aria-orientation",
  ariaPlaceholder: "aria-placeholder",
  ariaPressed: "aria-pressed",
  ariaReadonly: "aria-readonly",
  ariaRequired: "aria-required",
  ariaSelected: "aria-selected",
  ariaSort: "aria-sort",
  ariaValuemax: "aria-valuemax",
  ariaValuemin: "aria-valuemin",
  ariaValuenow: "aria-valuenow",
  ariaValuetext: "aria-valuetext",
  ariaBusy: "aria-busy",
  ariaLive: "aria-live",
  ariaRelevant: "aria-relevant",
  ariaAtomic: "aria-atomic",
  ariaDropeffect: "aria-dropeffect",
  ariaGrabbed: "aria-grabbed",
  ariaActivedescendant: "aria-activedescendant",
  ariaColcount: "aria-colcount",
  ariaColindex: "aria-colindex",
  ariaColspan: "aria-colspan",
  ariaControls: "aria-controls",
  ariaDescribedby: "aria-describedby",
  ariaDescription: "aria-description",
  ariaDetails: "aria-details",
  ariaFlowto: "aria-flowto",
  ariaLabelledby: "aria-labelledby",
  ariaOwns: "aria-owns",
  ariaPosinset: "aria-posinset",
  ariaRowcount: "aria-rowcount",
  ariaRowindex: "aria-rowindex",
  ariaRowspan: "aria-rowspan",
  ariaSetsize: "aria-setsize",
}

/**
 * @brief Recover HTML attribute name from CamelCase to kebab-case
 * @param name
 * @returns HTML attribute name
 */
export function recoverHTMLAttrName(name: string): string {
  return alteredAttrMap[name as keyof typeof alteredAttrMap] || name
}
