import * as htmlTag from "./htmlTag"

declare global {
  const a: typeof htmlTag.a
  const abbr: typeof htmlTag.abbr
  const address: typeof htmlTag.address
  const area: typeof htmlTag.area
  const article: typeof htmlTag.article
  const aside: typeof htmlTag.aside
  const audio: typeof htmlTag.audio
  const b: typeof htmlTag.b
  const base: typeof htmlTag.base
  const bdi: typeof htmlTag.bdi
  const bdo: typeof htmlTag.bdo
  const blockquote: typeof htmlTag.blockquote
  const body: typeof htmlTag.body
  const br: typeof htmlTag.br
  const button: typeof htmlTag.button
  const canvas: typeof htmlTag.canvas
  const caption: typeof htmlTag.caption
  const cite: typeof htmlTag.cite
  const code: typeof htmlTag.code
  const col: typeof htmlTag.col
  const colgroup: typeof htmlTag.colgroup
  const data: typeof htmlTag.data
  const datalist: typeof htmlTag.datalist
  const dd: typeof htmlTag.dd
  const del: typeof htmlTag.del
  const details: typeof htmlTag.details
  const dfn: typeof htmlTag.dfn
  const dialog: typeof htmlTag.dialog
  const div: typeof htmlTag.div
  const dl: typeof htmlTag.dl
  const dt: typeof htmlTag.dt
  const em: typeof htmlTag.em
  const embed: typeof htmlTag.embed
  const fieldset: typeof htmlTag.fieldset
  const figcaption: typeof htmlTag.figcaption
  const figure: typeof htmlTag.figure
  const footer: typeof htmlTag.footer
  const form: typeof htmlTag.form
  const h1: typeof htmlTag.h1
  const h2: typeof htmlTag.h2
  const h3: typeof htmlTag.h3
  const h4: typeof htmlTag.h4
  const h5: typeof htmlTag.h5
  const h6: typeof htmlTag.h6
  const head: typeof htmlTag.head
  const header: typeof htmlTag.header
  const hgroup: typeof htmlTag.hgroup
  const hr: typeof htmlTag.hr
  const html: typeof htmlTag.html
  const i: typeof htmlTag.i
  const iframe: typeof htmlTag.iframe
  const img: typeof htmlTag.img
  const input: typeof htmlTag.input
  const ins: typeof htmlTag.ins
  const kbd: typeof htmlTag.kbd
  const label: typeof htmlTag.label
  const legend: typeof htmlTag.legend
  const li: typeof htmlTag.li
  const link: typeof htmlTag.link
  const main: typeof htmlTag.main
  const map: typeof htmlTag.map
  const mark: typeof htmlTag.mark
  const menu: typeof htmlTag.menu
  const meta: typeof htmlTag.meta
  const meter: typeof htmlTag.meter
  const nav: typeof htmlTag.nav
  const noscript: typeof htmlTag.noscript
  const object: typeof htmlTag.object
  const ol: typeof htmlTag.ol
  const optgroup: typeof htmlTag.optgroup
  const option: typeof htmlTag.option
  const output: typeof htmlTag.output
  const p: typeof htmlTag.p
  const picture: typeof htmlTag.picture
  const pre: typeof htmlTag.pre
  const progress: typeof htmlTag.progress
  const q: typeof htmlTag.q
  const rp: typeof htmlTag.rp
  const rt: typeof htmlTag.rt
  const ruby: typeof htmlTag.ruby
  const s: typeof htmlTag.s
  const samp: typeof htmlTag.samp
  const script: typeof htmlTag.script
  const section: typeof htmlTag.section
  const select: typeof htmlTag.select
  const slot: typeof htmlTag.slot
  const small: typeof htmlTag.small
  const source: typeof htmlTag.source
  const span: typeof htmlTag.span
  const strong: typeof htmlTag.strong
  const style: typeof htmlTag.style
  const sub: typeof htmlTag.sub
  const summary: typeof htmlTag.summary
  const sup: typeof htmlTag.sup
  const table: typeof htmlTag.table
  const tbody: typeof htmlTag.tbody
  const td: typeof htmlTag.td
  const template: typeof htmlTag.template
  const textarea: typeof htmlTag.textarea
  const tfoot: typeof htmlTag.tfoot
  const th: typeof htmlTag.th
  const thead: typeof htmlTag.thead
  const time: typeof htmlTag.time
  const title: typeof htmlTag.title
  const tr: typeof htmlTag.tr
  const track: typeof htmlTag.track
  const u: typeof htmlTag.u
  const ul: typeof htmlTag.ul
  const var_: typeof htmlTag.var_
  const video: typeof htmlTag.video
  const wbr: typeof htmlTag.wbr
  const acronym: typeof htmlTag.acronym
  const applet: typeof htmlTag.applet
  const basefont: typeof htmlTag.basefont
  const bgsound: typeof htmlTag.bgsound
  const big: typeof htmlTag.big
  const blink: typeof htmlTag.blink
  const center: typeof htmlTag.center
  const dir: typeof htmlTag.dir
  const font: typeof htmlTag.font
  const frame: typeof htmlTag.frame
  const frameset: typeof htmlTag.frameset
  const isindex: typeof htmlTag.isindex
  const keygen: typeof htmlTag.keygen
  const listing: typeof htmlTag.listing
  const marquee: typeof htmlTag.marquee
  const menuitem: typeof htmlTag.menuitem
  const multicol: typeof htmlTag.multicol
  const nextid: typeof htmlTag.nextid
  const nobr: typeof htmlTag.nobr
  const noembed: typeof htmlTag.noembed
  const noframes: typeof htmlTag.noframes
  const param: typeof htmlTag.param
  const plaintext: typeof htmlTag.plaintext
  const rb: typeof htmlTag.rb
  const rtc: typeof htmlTag.rtc
  const spacer: typeof htmlTag.spacer
  const strike: typeof htmlTag.strike
  const tt: typeof htmlTag.tt
  const xmp: typeof htmlTag.xmp
  const animate: typeof htmlTag.animate
  const animateMotion: typeof htmlTag.animateMotion
  const animateTransform: typeof htmlTag.animateTransform
  const circle: typeof htmlTag.circle
  const clipPath: typeof htmlTag.clipPath
  const defs: typeof htmlTag.defs
  const desc: typeof htmlTag.desc
  const ellipse: typeof htmlTag.ellipse
  const feBlend: typeof htmlTag.feBlend
  const feColorMatrix: typeof htmlTag.feColorMatrix
  const feComponentTransfer: typeof htmlTag.feComponentTransfer
  const feComposite: typeof htmlTag.feComposite
  const feConvolveMatrix: typeof htmlTag.feConvolveMatrix
  const feDiffuseLighting: typeof htmlTag.feDiffuseLighting
  const feDisplacementMap: typeof htmlTag.feDisplacementMap
  const feDistantLight: typeof htmlTag.feDistantLight
  const feDropShadow: typeof htmlTag.feDropShadow
  const feFlood: typeof htmlTag.feFlood
  const feFuncA: typeof htmlTag.feFuncA
  const feFuncB: typeof htmlTag.feFuncB
  const feFuncG: typeof htmlTag.feFuncG
  const feFuncR: typeof htmlTag.feFuncR
  const feGaussianBlur: typeof htmlTag.feGaussianBlur
  const feImage: typeof htmlTag.feImage
  const feMerge: typeof htmlTag.feMerge
  const feMergeNode: typeof htmlTag.feMergeNode
  const feMorphology: typeof htmlTag.feMorphology
  const feOffset: typeof htmlTag.feOffset
  const fePointLight: typeof htmlTag.fePointLight
  const feSpecularLighting: typeof htmlTag.feSpecularLighting
  const feSpotLight: typeof htmlTag.feSpotLight
  const feTile: typeof htmlTag.feTile
  const feTurbulence: typeof htmlTag.feTurbulence
  const filter: typeof htmlTag.filter
  const foreignObject: typeof htmlTag.foreignObject
  const g: typeof htmlTag.g
  const image: typeof htmlTag.image
  const line: typeof htmlTag.line
  const linearGradient: typeof htmlTag.linearGradient
  const marker: typeof htmlTag.marker
  const mask: typeof htmlTag.mask
  const metadata: typeof htmlTag.metadata
  const mpath: typeof htmlTag.mpath
  const path: typeof htmlTag.path
  const pattern: typeof htmlTag.pattern
  const polygon: typeof htmlTag.polygon
  const polyline: typeof htmlTag.polyline
  const radialGradient: typeof htmlTag.radialGradient
  const rect: typeof htmlTag.rect
  const set: typeof htmlTag.set
  // const stop: typeof htmlTag.stop
  const svg: typeof htmlTag.svg
  const switch_: typeof htmlTag.switch_
  const symbol: typeof htmlTag.symbol
  const text: typeof htmlTag.text
  const textPath: typeof htmlTag.textPath
  const tspan: typeof htmlTag.tspan
  const view: typeof htmlTag.view
}

export {}
