// @ts-ignore
function getExportTags() {
    const availableHTMLTags = "a,abbr,address,area,article,aside,audio,b,base,bdi,bdo,blockquote,body,br,button,canvas,caption,cite,code,col,colgroup,data,datalist,dd,del,details,dfn,dialog,div,dl,dt,em,embed,fieldset,figcaption,figure,footer,form,h1,h2,h3,h4,h5,h6,head,header,hgroup,hr,html,i,iframe,img,input,ins,kbd,label,legend,li,link,main,map,mark,menu,meta,meter,nav,noscript,object,ol,optgroup,option,output,p,param,picture,pre,progress,q,rp,rt,ruby,s,samp,script,section,select,slot,small,source,span,strong,style,sub,summary,sup,table,tbody,td,template,textarea,tfoot,th,thead,time,title,tr,track,u,ul,var,video,wbr\n"
    const availableHTMLTagList = availableHTMLTags.split(",")
    for (let tag of availableHTMLTagList) {
        console.log(`export const ${tag} = undefined as any`)
    }
}
// getExportTags()

// ----
export const State = undefined as any
export const PropState = undefined as any
export const EnvState = undefined as any
export const Prop = undefined as any
export const Env =  undefined as any
export const _ = undefined as any
export const env = undefined as any

// ---- html tags
export const a = undefined as any
export const abbr = undefined as any
export const address = undefined as any
export const area = undefined as any
export const article = undefined as any
export const aside = undefined as any
export const audio = undefined as any
export const b = undefined as any
export const base = undefined as any
export const bdi = undefined as any
export const bdo = undefined as any
export const blockquote = undefined as any
export const body = undefined as any
export const br = undefined as any
export const button = undefined as any
export const canvas = undefined as any
export const caption = undefined as any
export const cite = undefined as any
export const code = undefined as any
export const col = undefined as any
export const colgroup = undefined as any
export const data = undefined as any
export const datalist = undefined as any
export const dd = undefined as any
export const del = undefined as any
export const details = undefined as any
export const dfn = undefined as any
export const dialog = undefined as any
export const div = undefined as any
export const dl = undefined as any
export const dt = undefined as any
export const em = undefined as any
export const embed = undefined as any
export const fieldset = undefined as any
export const figcaption = undefined as any
export const figure = undefined as any
export const footer = undefined as any
export const form = undefined as any
export const h1 = undefined as any
export const h2 = undefined as any
export const h3 = undefined as any
export const h4 = undefined as any
export const h5 = undefined as any
export const h6 = undefined as any
export const head = undefined as any
export const header = undefined as any
export const hgroup = undefined as any
export const hr = undefined as any
export const html = undefined as any
export const i = undefined as any
export const iframe = undefined as any
export const img = undefined as any
export const input = undefined as any
export const ins = undefined as any
export const kbd = undefined as any
export const label = undefined as any
export const legend = undefined as any
export const li = undefined as any
export const link = undefined as any
export const main = undefined as any
export const map = undefined as any
export const mark = undefined as any
export const menu = undefined as any
export const meta = undefined as any
export const meter = undefined as any
export const nav = undefined as any
export const noscript = undefined as any
export const object = undefined as any
export const ol = undefined as any
export const optgroup = undefined as any
export const option = undefined as any
export const output = undefined as any
export const p = undefined as any
export const param = undefined as any
export const picture = undefined as any
export const pre = undefined as any
export const progress = undefined as any
export const q = undefined as any
export const rp = undefined as any
export const rt = undefined as any
export const ruby = undefined as any
export const s = undefined as any
export const samp = undefined as any
export const script = undefined as any
export const section = undefined as any
export const select = undefined as any
export const slot = undefined as any
export const small = undefined as any
export const source = undefined as any
export const span = undefined as any
export const strong = undefined as any
export const style = undefined as any
export const sub = undefined as any
export const summary = undefined as any
export const sup = undefined as any
export const table = undefined as any
export const tbody = undefined as any
export const td = undefined as any
export const template = undefined as any
export const textarea = undefined as any
export const tfoot = undefined as any
export const th = undefined as any
export const thead = undefined as any
export const time = undefined as any
export const title = undefined as any
export const tr = undefined as any
export const track = undefined as any
export const u = undefined as any
export const ul = undefined as any
export const video = undefined as any
export const wbr = undefined as any

