export const devMode = process.env.NODE_ENV === "development"

export const defaultHTMLTags = [
  "a",
  "abbr",
  "address",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "bdi",
  "bdo",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "div",
  "dl",
  "dt",
  "em",
  "embed",
  "fieldset",
  "figcaption",
  "figure",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hgroup",
  "hr",
  "html",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "kbd",
  "label",
  "legend",
  "li",
  "link",
  "main",
  "map",
  "mark",
  "menu",
  "meta",
  "meter",
  "nav",
  "noscript",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "picture",
  "pre",
  "progress",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "script",
  "section",
  "select",
  "slot",
  "small",
  "source",
  "span",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "u",
  "ul",
  "var",
  "video",
  "wbr",
  "acronym",
  "applet",
  "basefont",
  "bgsound",
  "big",
  "blink",
  "center",
  "dir",
  "font",
  "frame",
  "frameset",
  "isindex",
  "keygen",
  "listing",
  "marquee",
  "menuitem",
  "multicol",
  "nextid",
  "nobr",
  "noembed",
  "noframes",
  "param",
  "plaintext",
  "rb",
  "rtc",
  "spacer",
  "strike",
  "tt",
  "xmp",
  "animate",
  "animateMotion",
  "animateTransform",
  "circle",
  "clipPath",
  "defs",
  "desc",
  "ellipse",
  "feBlend",
  "feColorMatrix",
  "feComponentTransfer",
  "feComposite",
  "feConvolveMatrix",
  "feDiffuseLighting",
  "feDisplacementMap",
  "feDistantLight",
  "feDropShadow",
  "feFlood",
  "feFuncA",
  "feFuncB",
  "feFuncG",
  "feFuncR",
  "feGaussianBlur",
  "feImage",
  "feMerge",
  "feMergeNode",
  "feMorphology",
  "feOffset",
  "fePointLight",
  "feSpecularLighting",
  "feSpotLight",
  "feTile",
  "feTurbulence",
  "filter",
  "foreignObject",
  "g",
  "image",
  "line",
  "linearGradient",
  "marker",
  "mask",
  "metadata",
  "mpath",
  "path",
  "pattern",
  "polygon",
  "polyline",
  "radialGradient",
  "rect",
  "set",
  "stop",
  "svg",
  "switch",
  "symbol",
  "text",
  "textPath",
  "tspan",
  "use",
  "view",
]

export const availableDecoNames = [
  "Static",
  "Prop",
  "Env",
  "Content",
  "Children",
]
export const dlightDefaultPackageName = "@dlightjs/dlight"
export const importMap = Object.fromEntries(
  [
    "createTemplate",
    "setStyle",
    "setDataset",
    "setEvent",
    "setHTMLProp",
    "setHTMLAttr",
    "setHTMLProps",
    "setHTMLAttrs",
    "insertNode",
    "createElement",
    "ForNode",
    "CondNode",
    "EnvNode",
    "createTextNode",
    "updateText",
    "ExpNode",
    "PropView",
    "SubViewNode",
  ].map((funcName, idx) =>
    devMode ? [funcName, funcName] : [funcName, `$${idx}$`]
  )
)

/**
 * @brief HTML attribute name map, from CamelCase to kebab-case
 */
export const defaultAlteredAttrMap = {
  acceptCharset: "accept-charset",
  colSpan: "colspan",
  contentEditable: "contenteditable",
  formAction: "formaction",
  formEnctype: "formenctype",
  formMethod: "formmethod",
  formNoValidate: "formnovalidate",
  formTarget: "formtarget",
  httpEquiv: "http-equiv",
  intrinsicSize: "intrinsicsize",
  inputMode: "inputmode",
  itemProp: "itemprop",
  maxLength: "maxlength",
  minLength: "minlength",
  noValidate: "novalidate",
  playsInline: "playsinline",
  referrerPolicy: "referrerpolicy",
  rowSpan: "rowspan",
  tabIndex: "tabindex",
  ariaAutocomplete: "aria-autocomplete",
  ariaChecked: "aria-checked",
  ariaDisabled: "aria-disabled",
  ariaErrorMessage: "aria-errormessage",
  ariaExpanded: "aria-expanded",
  ariaHasPopup: "aria-haspopup",
  ariaHidden: "aria-hidden",
  ariaInvalid: "aria-invalid",
  ariaLabel: "aria-label",
  ariaLevel: "aria-level",
  ariaModal: "aria-modal",
  ariaMultiline: "aria-multiline",
  ariaMultiSelectable: "aria-multiselectable",
  ariaOrientation: "aria-orientation",
  ariaPlaceholder: "aria-placeholder",
  ariaPressed: "aria-pressed",
  ariaReadonly: "aria-readonly",
  ariaRequired: "aria-required",
  ariaSelected: "aria-selected",
  ariaSort: "aria-sort",
  ariaValuemax: "aria-valuemax",
  ariaValuemin: "aria-valuemin",
  ariaValueNow: "aria-valuenow",
  ariaValueText: "aria-valuetext",
  ariaBusy: "aria-busy",
  ariaLive: "aria-live",
  ariaRelevant: "aria-relevant",
  ariaAtomic: "aria-atomic",
  ariaDropEffect: "aria-dropeffect",
  ariaGrabbed: "aria-grabbed",
  ariaActiveDescendant: "aria-activedescendant",
  ariaColCount: "aria-colcount",
  ariaColIndex: "aria-colindex",
  ariaColSpan: "aria-colspan",
  ariaControls: "aria-controls",
  ariaDescribedBy: "aria-describedby",
  ariaDescription: "aria-description",
  ariaDetails: "aria-details",
  ariaFlowTo: "aria-flowto",
  ariaLabelLedBy: "aria-labelledby",
  ariaOwns: "aria-owns",
  ariaPosInset: "aria-posinset",
  ariaRowCount: "aria-rowcount",
  ariaRowIndex: "aria-rowindex",
  ariaRowSpan: "aria-rowspan",
  ariaSetSize: "aria-setsize",
}

/**
 * @brief HTML internal attribute map, can be accessed as js property
 */
export const defaultAttributeMap = {
  // ---- Other property as attribute
  textContent: ["*"],
  innerHTML: ["*"],
  // ---- Source: https://developer.mozilla.org/zh-CN/docs/Web/HTML/Attributes
  accept: ["form", "input"],
  // ---- Original: accept-charset
  acceptCharset: ["form"],
  accesskey: ["*"],
  action: ["form"],
  align: [
    "caption",
    "col",
    "colgroup",
    "hr",
    "iframe",
    "img",
    "table",
    "tbody",
    "td",
    "tfoot",
    "th",
    "thead",
    "tr",
  ],
  allow: ["iframe"],
  alt: ["area", "img", "input"],
  async: ["script"],
  autocapitalize: ["*"],
  autocomplete: ["form", "input", "select", "textarea"],
  autofocus: ["button", "input", "select", "textarea"],
  autoplay: ["audio", "video"],
  background: ["body", "table", "td", "th"],
  // ---- Original: base
  bgColor: [
    "body",
    "col",
    "colgroup",
    "marquee",
    "table",
    "tbody",
    "tfoot",
    "td",
    "th",
    "tr",
  ],
  border: ["img", "object", "table"],
  buffered: ["audio", "video"],
  capture: ["input"],
  charset: ["meta"],
  checked: ["input"],
  cite: ["blockquote", "del", "ins", "q"],
  class: ["*"],
  color: ["font", "hr"],
  cols: ["textarea"],
  // ---- Original: colspan
  colSpan: ["td", "th"],
  content: ["meta"],
  // ---- Original: contenteditable
  contentEditable: ["*"],
  contextmenu: ["*"],
  controls: ["audio", "video"],
  coords: ["area"],
  crossOrigin: ["audio", "img", "link", "script", "video"],
  csp: ["iframe"],
  data: ["object"],
  // ---- Original: datetime
  dateTime: ["del", "ins", "time"],
  decoding: ["img"],
  default: ["track"],
  defer: ["script"],
  dir: ["*"],
  dirname: ["input", "textarea"],
  disabled: [
    "button",
    "fieldset",
    "input",
    "optgroup",
    "option",
    "select",
    "textarea",
  ],
  download: ["a", "area"],
  draggable: ["*"],
  enctype: ["form"],
  // ---- Original: enterkeyhint
  enterKeyHint: ["textarea", "contenteditable"],
  for: ["label", "output"],
  form: [
    "button",
    "fieldset",
    "input",
    "label",
    "meter",
    "object",
    "output",
    "progress",
    "select",
    "textarea",
  ],
  // ---- Original: formaction
  formAction: ["input", "button"],
  // ---- Original: formenctype
  formEnctype: ["button", "input"],
  // ---- Original: formmethod
  formMethod: ["button", "input"],
  // ---- Original: formnovalidate
  formNoValidate: ["button", "input"],
  // ---- Original: formtarget
  formTarget: ["button", "input"],
  headers: ["td", "th"],
  height: ["canvas", "embed", "iframe", "img", "input", "object", "video"],
  hidden: ["*"],
  high: ["meter"],
  href: ["a", "area", "base", "link"],
  hreflang: ["a", "link"],
  // ---- Original: http-equiv
  httpEquiv: ["meta"],
  id: ["*"],
  integrity: ["link", "script"],
  // ---- Original: intrinsicsize
  intrinsicSize: ["img"],
  // ---- Original: inputmode
  inputMode: ["textarea", "contenteditable"],
  ismap: ["img"],
  // ---- Original: itemprop
  itemProp: ["*"],
  kind: ["track"],
  label: ["optgroup", "option", "track"],
  lang: ["*"],
  language: ["script"],
  loading: ["img", "iframe"],
  list: ["input"],
  loop: ["audio", "marquee", "video"],
  low: ["meter"],
  manifest: ["html"],
  max: ["input", "meter", "progress"],
  // ---- Original: maxlength
  maxLength: ["input", "textarea"],
  // ---- Original: minlength
  minLength: ["input", "textarea"],
  media: ["a", "area", "link", "source", "style"],
  method: ["form"],
  min: ["input", "meter"],
  multiple: ["input", "select"],
  muted: ["audio", "video"],
  name: [
    "button",
    "form",
    "fieldset",
    "iframe",
    "input",
    "object",
    "output",
    "select",
    "textarea",
    "map",
    "meta",
    "param",
  ],
  // ---- Original: novalidate
  noValidate: ["form"],
  open: ["details", "dialog"],
  optimum: ["meter"],
  pattern: ["input"],
  ping: ["a", "area"],
  placeholder: ["input", "textarea"],
  // ---- Original: playsinline
  playsInline: ["video"],
  poster: ["video"],
  preload: ["audio", "video"],
  readonly: ["input", "textarea"],
  // ---- Original: referrerpolicy
  referrerPolicy: ["a", "area", "iframe", "img", "link", "script"],
  rel: ["a", "area", "link"],
  required: ["input", "select", "textarea"],
  reversed: ["ol"],
  role: ["*"],
  rows: ["textarea"],
  // ---- Original: rowspan
  rowSpan: ["td", "th"],
  sandbox: ["iframe"],
  scope: ["th"],
  scoped: ["style"],
  selected: ["option"],
  shape: ["a", "area"],
  size: ["input", "select"],
  sizes: ["link", "img", "source"],
  slot: ["*"],
  span: ["col", "colgroup"],
  spellcheck: ["*"],
  src: [
    "audio",
    "embed",
    "iframe",
    "img",
    "input",
    "script",
    "source",
    "track",
    "video",
  ],
  srcdoc: ["iframe"],
  srclang: ["track"],
  srcset: ["img", "source"],
  start: ["ol"],
  step: ["input"],
  style: ["*"],
  summary: ["table"],
  // ---- Original: tabindex
  tabIndex: ["*"],
  target: ["a", "area", "base", "form"],
  title: ["*"],
  translate: ["*"],
  type: [
    "button",
    "input",
    "embed",
    "object",
    "ol",
    "script",
    "source",
    "style",
    "menu",
    "link",
  ],
  usemap: ["img", "input", "object"],
  value: [
    "button",
    "data",
    "input",
    "li",
    "meter",
    "option",
    "progress",
    "param",
    "text" /** extra for TextNode */,
  ],
  width: ["canvas", "embed", "iframe", "img", "input", "object", "video"],
  wrap: ["textarea"],
  // --- ARIA attributes
  //     Source: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes
  ariaAutocomplete: ["*"],
  ariaChecked: ["*"],
  ariaDisabled: ["*"],
  ariaErrorMessage: ["*"],
  ariaExpanded: ["*"],
  ariaHasPopup: ["*"],
  ariaHidden: ["*"],
  ariaInvalid: ["*"],
  ariaLabel: ["*"],
  ariaLevel: ["*"],
  ariaModal: ["*"],
  ariaMultiline: ["*"],
  ariaMultiSelectable: ["*"],
  ariaOrientation: ["*"],
  ariaPlaceholder: ["*"],
  ariaPressed: ["*"],
  ariaReadonly: ["*"],
  ariaRequired: ["*"],
  ariaSelected: ["*"],
  ariaSort: ["*"],
  ariaValuemax: ["*"],
  ariaValuemin: ["*"],
  ariaValueNow: ["*"],
  ariaValueText: ["*"],
  ariaBusy: ["*"],
  ariaLive: ["*"],
  ariaRelevant: ["*"],
  ariaAtomic: ["*"],
  ariaDropEffect: ["*"],
  ariaGrabbed: ["*"],
  ariaActiveDescendant: ["*"],
  ariaColCount: ["*"],
  ariaColIndex: ["*"],
  ariaColSpan: ["*"],
  ariaControls: ["*"],
  ariaDescribedBy: ["*"],
  ariaDescription: ["*"],
  ariaDetails: ["*"],
  ariaFlowTo: ["*"],
  ariaLabelledBy: ["*"],
  ariaOwns: ["*"],
  ariaPosInset: ["*"],
  ariaRowCount: ["*"],
  ariaRowIndex: ["*"],
  ariaRowSpan: ["*"],
  ariaSetSize: ["*"],
}
